---
name: Docker

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]

jobs:
  buildx:
    name: Build container
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up emulation
        uses: docker/setup-qemu-action@v3
      - name: Set up buildx command
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build container (alpine/latest)
        if: ${{ github.ref == 'refs/heads/master' }}
        run: 'docker buildx build -f Dockerfile-alpine --push -t ghostunnel/ghostunnel:latest -t ghostunnel/ghostunnel:latest-alpine --platform linux/amd64,linux/arm64,linux/arm/v7 .'
      - name: Build container (debian/latest)
        if: ${{ github.ref == 'refs/heads/master' }}
        run: 'docker buildx build -f Dockerfile-debian --push -t ghostunnel/ghostunnel:latest-debian --platform linux/amd64,linux/arm64,linux/arm/v7 .'
      - name: Build container (alpine/tagged)
        if: ${{ github.ref != 'refs/heads/master' }}
        run: 'docker buildx build -f Dockerfile-alpine --push -t ghostunnel/ghostunnel:$(git describe --tags --abbrev=0) -t ghostunnel/ghostunnel:$(git describe --tags --abbrev=0)-alpine --platform linux/amd64,linux/arm64,linux/arm/v7 .'
      - name: Build container (debian/tagged)
        if: ${{ github.ref != 'refs/heads/master' }}
        run: 'docker buildx build -f Dockerfile-debian --push -t ghostunnel/ghostunnel:$(git describe --tags --abbrev=0)-debian --platform linux/amd64,linux/arm64,linux/arm/v7 .'
